apiVersion: apps/v1beta1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: pet-clinic
spec:
  selector:
    matchLabels:
      app: pet-clinic-app
  replicas: 3
  template:
    metadata:
      labels:
        app: pet-clinic-app
    spec:
      containers:
      - name: pet-clinic-app
        image: katson95/pet-clinic:latest
        ports:
        - containerPort: 8080
          name: server
        - containerPort: 8081
          name: management
